name: Test API Routes

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    # Install backend dependencies
    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the backend
    - name: Start Backend
      run: |
        nohup python app.py &
        sleep 10  # Wait for the server to start

    # Run API tests
    - name: Run API Tests
      env:
        BASE_URL: "http://localhost:5000"
      run: |
        pytest tests/

    # Cleanup
    - name: Kill Backend
      if: always()
      run: |
        pkill -f "python app.py"
