name: Test API Routes

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      app:
        image: taimooranwar/mlops-backend:latest
        ports:
          - 5000:5000
        env:
          MONGO_URI: "mongodb://mongo:27017/"
          JWT_SECRET_KEY: "test_secret"
        options: >-
          --health-cmd "curl --fail http://localhost:5000/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests

    # Run API tests
    - name: Run API Tests
      env:
        BASE_URL: "http://localhost:5000"
      run: |
        pytest tests/
